#!/bin/sh

die() {
    status="$1"
    shift
    warn "$0: $@"
    exit "$status"
}

warn() {
    echo $@ 1>&2
}

edit_safedirs() {
    $EDITOR "$safedir_config"
}

help() {
    echo $USAGE
}

picker() {
    dmenu $ignore_case $dmenu_args -fn "$font"
}

make_safedir_config() {
    old_umask=$(umask)
    umask 0077
    echo '# put full paths to safe directories here' >"$safedir_config"
    umask $old_umask
    edit_safedirs
}

make_config() {
    old_umask=$(umask)
    umask 0077
    mkdir -p "$config" || die 1 "Can't make $config"
    umask $old_umask
}

require_private() {
    ls -ld "$1" | awk '{print $1}' | grep -e '------$' >/dev/null \
    || die 1 "$1 should be not be readable or writable by others"
}

my_dialog() {
    dialog --title "Password selector" \
    --menu "pick a site for a password" \
    20 51 12 \
    foo bar \
    baz quz \
    thing one \
    thing2 two \
    2> foo

    retval=$?
    cat foo
}

USAGE="$0 [OPTIONS] [REGEX]"

config="$HOME/.config/pw"
test -d "$config" || make_config

safedir_config="$config/safedir"

while [ ! -f "$safedir_config" ]; do
    make_safedir_config
done
require_private "$safedir_config"

safedirs="$(grep -v '^#' "$safedir_config")"

f_Group_Title=1
f_Username=2
f_Password=3
f_URL=4
f_AutoType=5
f_Created_Time=6
f_Password_Modified_Time=7
f_Last_Access_Time=8
f_Password_Expiry_Date=9
f_Password_Expiry_Interval=10
f_Record_Modified_Time=11
f_Password_Policy=12
f_Password_Policy_Name=13
f_History=14
f_Run_Command=15
f_DCA=16
f_Shift_DCA=17
f_e_mail=18
f_Protected=19
f_Symbols=20
f_Notes=21

field=$f_Password
ignore_case="-i"
font='-*-dejavu sans-medium-r-'
lines='45'
dmenu_args="-l $lines"

clipboard="xclip -i"

while [ $# -gt 0 ]; do
    case "$1" in 
      --help)
        help
        exit
        ;; 
      --user)
        field=$f_Username
        shift
        ;; 
      --url)
        field=$f_URL
        shift
        ;;
      --edit-safedirs)
        edit_safedirs
        exit $?
        ;;
      --case-sensitive)
        ignore_case=""
        shift
        ;;
      -*)
        die 1 "unknown flag $1 - $USAGE"
        shift
        break
        ;;
      *)
        break
        ;;
    esac
done

request='.'
test $# -eq 1 && request="$1"

#{ while [ read <$safedir_config ]; do
#    grep -v -h '^#' "$REPLY/"*
#done } |\

#my_dialog

for i in "$config" "$safedir_config" "$safedirs" "$safedirs/"*; do
    require_private "$i"
done

grep -v -h '^#' "$safedirs/"* |\
grep $ignore_case $request |\
picker |\
cut -f $field |\
$clipboard

