#!/bin/sh

die() {
    status="$1"
    shift
    warn "$0: $@"
    exit "$status"
}

warn() {
    echo $@ 1>&2
}

add_safedir() {
    $EDITOR "$safedir_config"
}

make_safedir_config() {
    echo '# put full paths to safe directories here' >"$safedir_config"
    add_safedir
}

USAGE="$0 [-u] [-url]"

config="$HOME/.config/pw"
test -d "$config" || mkdir -p "$config" || die 1 "Can't make $config"

safedir_config="$config/safedir"

while [ ! -f "$safedir_config" ]; do
    make_safedir_config
done

safedirs="$(grep -v '^#' "$safedir_config")"

f_Group_Title=1
f_Username=2
f_Password=3
f_URL=4
f_AutoType=5
f_Created_Time=6
f_Password_Modified_Time=7
f_Last_Access_Time=8
f_Password_Expiry_Date=9
f_Password_Expiry_Interval=10
f_Record_Modified_Time=11
f_Password_Policy=12
f_Password_Policy_Name=13
f_History=14
f_Run_Command=15
f_DCA=16
f_Shift_DCA=17
f_e_mail=18
f_Protected=19
f_Symbols=20
f_Notes=21

field=$f_Password
ignore_case="-i"
dmenu_args="-l 45"
clipboard="xclip -i"

while [ $# -gt 0 ]; do
    case "$1" in 
      --user)
        field=$f_Username
        shift
        ;; 
      --url)
        field=$f_URL
        shift
        ;;
      --add-safedir)
        add_safedir
        exit
        ;;
      --case-sensitive)
        ignore_case=""
        shift
        ;;
      -*)
        die 1 "unknown flag $1 - $USAGE"
        shift
        break
        ;;
      *)
        break
        ;;
    esac
done

picker="dmenu $ignore_case $dmenu_args"

request='.'
test $# -eq 1 && request="$1"

#{ while [ read <$safedir_config ]; do
#    grep -v -h '^#' "$REPLY/"*
#done } |\

grep -v -h '^#' "$safedirs/"* |\
grep $ignore_case $request |\
$picker |\
awk -F'	' '{print $'$field'}' |\
$clipboard

