.# vim: ft=nroff
.TH pw 1 pw\-__0.0.1
.SH NAME
pw \- simple password manager
.SH SYNOPSIS
.B pw [OPTIONS] [REGEX]
.SH DESCRIPTION
.B pw
opens a menu of passwords,
and puts the selected one in the clipboard.
It currently does not encrypt the password file.
.SH OPTIONS
.TP 5
--help 
Print a brief usage message.
.TP 5
--user
Get the user name instead of the password.
.TP 5
--url
Get the url instead of the password.
.TP 5
--edit-safedirs
Edit the location of the safedirs.
.TP 5
--case-sensitive
Make searches case sensitive.
.SH EXAMPLES
.LP
.B pw --user
.SH EXIT STATUS
exits non-zero on error.
.SH AUTHOR
Noah Birnel
.SH HISTORY
.SH FILES
.LP
.B $HOME/.config/pw/safedir
Where the location of the safes is stored.
.LP
.B [safes]
The safes,
which are tab delimited,
based on the PasswordSafe export format.
.SH BUGS
Can only read one safes directory. 
Requires X to be running.
Safes are not encrypted.
Probably others.
.SH DEPENDANCIES
.IR http://dl.suckless.org/tools/dmenu-4.5.tar.gz
.SH SEE ALSO
.TP
.BR dmenu(1)
.SH LICENSE
Copyright 2014 Noah Birnel
.sp
DWTFYW

